# Linking the drive

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


# Numpy
- It means numerical python.
- It's the linear algebra library for python.
- It's fast, as it has bindings with C libraries.
- Almost all the libraries in pydata ecosystem rely on it because Numpy was one of their building blocks.

### The Old School
- For python idle version you can install numpy using:
   ```
   pip  install numpy
   ```
- For anaconda version you can install using: 
```
conda install numpy
```










# Use of numpy?
- Numpy arrays.
- It's of two types:
  - Vectors: 1-D array.
  - Matrices: 2-D ( But a matrics can have only one row or one column.)




# Let's get started


In [4]:
# list
my_list = [1,2,3]
my_list

[1, 2, 3]

## Importing the libraries

In [3]:
import numpy as np

Creating a numpy array

In [5]:
np.array(my_list)

array([1, 2, 3])

In [6]:
arr = np.array(my_list)

In [7]:
arr
# vector

array([1, 2, 3])

### Creating matrices

In [8]:
# 2-D List
my_mat = [[1, 2, 3] ,
          [4, 5, 6] ,
          [7, 8, 9] ]

In [9]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
mat = np.array(my_mat)

In [11]:
mat

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Creating evenly spaced array

- It takes two required argument and one optional argument.
  - 1st argument: start of array.
  - 2nd argument: end point(not inclusive).
  - 3rd argument: optional step size.

In [15]:
np.arange(0,20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [14]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Creating array of zeroes
- For creating higher dimension zeroes array you need to pass on tuple with desired row and column values.

In [19]:
np.zeros(100)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
np.zeros((10,7))

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

### Linspace

start 1
end 2

linspace 5

1 , 1.2 , 1.4, 1.6 1.8

In [20]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

### Identity matrices

all diagonal elements 


 1  0  0
 0  1  0
 0  0  1

matrics n * m for I: n == m

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### array of random numbers

#### rand:
- It creates n elements array with random values in between 0 and 1.

In [24]:
np.random.rand(10)

array([0.42817615, 0.49193893, 0.25074048, 0.63649103, 0.38125367,
       0.74301638, 0.31459195, 0.92772087, 0.14473308, 0.80572563])

#### randn:
- It creates n elements array with random values from standard distribution.

In [25]:
np.random.randn(2)

array([-9.88282366e-04,  1.04158219e+00])

#### randint:
- it gives random integer values with n optional values.

In [26]:
np.random.randint(0,100)

2

In [27]:
np.random.randint(1,11,10)

array([ 4, 10,  8,  2, 10,  3,  7,  4,  3,  8])

#### reshape:

In [28]:
arr = np.arange(25)

In [29]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

#### max:

In [33]:
arr.max()

24

#### max index(argmax):

In [34]:
arr.argmax()

24

#### min:

In [35]:
arr.min()

0

#### min value index:

In [36]:
arr.argmin()

0

#### shape:

In [39]:
a = np.arange(10)

In [40]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
a.shape

(10,)

In [37]:
arr = arr.reshape(5,5)

In [38]:
arr.shape

(5, 5)

#### dtype:

In [42]:
arr.dtype

dtype('int64')

#### a click bait:

In [43]:
from numpy import random

In [44]:
random.randint(1,100)

70

In [45]:
from numpy.random import randint

randint(1,100)

50

# Numpy Indexing and selection

In [46]:
arr = np.arange(0,11)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### values by index:

In [50]:
arr[3]

3

#### slicing the array

In [53]:
arr[0:9]

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [54]:
arr[0:4]

array([0, 1, 2, 3])

In [55]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [56]:
arr[:5]

array([0, 1, 2, 3, 4])

#### Updating the values

In [57]:
arr[9] = 100

In [58]:
arr

array([  0,   1,   2,   3,   4,   5,   6,   7,   8, 100,  10])

In [59]:
arr[0:5] = 100

In [60]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8, 100,  10])

arr[0]   -->   [1]
arr[1]   -->   [2]
arr[2] ---->   [3]

In [96]:
arr[0:5] = [1,2,3,4,5]

In [97]:
arr

array([  1,   2,   3,   4,   5,  99,  99,  99,  99, 100,  10])

#### Slicing of an array

In [73]:
slice_of_an_array = arr[1:9]

In [74]:
slice_of_an_array

array([2, 3, 4, 5, 5, 6, 7, 8])

In [75]:
slice_of_an_array[:] = 99

In [76]:
slice_of_an_array

array([99, 99, 99, 99, 99, 99, 99, 99])

In [83]:
arr

array([  1,   2,   3,   4,   5,  99,  99,  99,  99, 100,  10])

#### .copy:

In [80]:
arr_copy = arr.copy()

In [81]:
arr_copy[:] = 0

In [82]:
arr_copy

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Working on 2-D array:

In [85]:
arr_2d = np.array([[1,2,3,4,5],#0
                   [6,7,8,9,10],#1
                   [11,12,13,14,15],#2
                   [16,17,18,19,20]])#3

In [86]:
arr_2d[2][1]

12

In [87]:
arr_2d[2,1]

12

In [88]:
arr_2d[3,4]

20

1:3 ---> rows
6 7 8 9 10
11 12 13 14 15

In [89]:
arr_2d[1:3,1:3]

array([[ 7,  8],
       [12, 13]])

In [90]:
arr_2d[1:,:2]

array([[ 6,  7],
       [11, 12],
       [16, 17]])

#### Bool values on array:

In [91]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [92]:
arr < 5

array([ True,  True,  True,  True, False, False, False, False, False,
       False, False])

In [93]:
bool_arr = arr > 5

In [94]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [95]:
arr[bool_arr]

array([ 99,  99,  99,  99, 100,  10])

In [98]:
np.arange(25).reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### Numpy operations:

#### adding arrays

In [100]:
arr = np.arange(0,11)

In [101]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [102]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [103]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

#### Subtracting arrays

In [104]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [105]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

#### array multiplication

In [106]:
arr * arr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [107]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

#### array division

In [108]:
arr/arr

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: invalid value encountered in true_divide
  """Entry point for launching an IPython kernel.


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [110]:
arr/10

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

#### power of an array

In [111]:
2 ** 2

4

In [112]:
arr ** arr

array([          1,           1,           4,          27,         256,
              3125,       46656,      823543,    16777216,   387420489,
       10000000000])

In [113]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

#### sqrt of an array

In [114]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

#### sin values of array

In [115]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

#### cosine values of an array

In [116]:
np.cos(arr)

array([ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
        0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026,
       -0.83907153])

#### log values of an array

In [117]:
np.log(arr)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:1: RuntimeWarning: divide by zero encountered in log
  """Entry point for launching an IPython kernel.


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

#### Ufunc numpy documentation: [link](https://numpy.org/doc/stable/reference/ufuncs.html)